### ISSUE TITLE
How to find the days of phase Moon

### ISSUE THREAD

**Issue by petrospap** [Hypnos3/suncalc3#1]
Hello, first I want to thank you for this very nice library!

For my question, I try to find the days of new moon, for example today: 28 November 2022 is “5 days young Moon”.
Is there any idea how to get those days?

BTW: I wish to have moon eclipses, seems like is most of calculations already exist 
astronomy.stackexchange.com/questions/231/what-is-the-formula-to-predict-lunar-and-solar-eclipses-accurately

Thank you

**Comment by jazztunes** [comment]
Assuming a fixed lunar cycle of 29.53058770576 days, you can multiply the phaseValue by that number to get the age of the moon in days.

--DH

### Sample code
```
var dt=new Date("28 November 2022");
var info=SunCalc.getMoonIllumination(dt);
console.log(info.phaseValue * 29.53058770576);
```

### Results:
```
4.747607392596853
```

Note: I did open what I believe to be a bug with phaseValue:  https://github.com/Hypnos3/suncalc3/issues/7

**Comment by petrospap** [comment]
Seems like phaseValue >  angle changes from negative to +
``const phaseValue = 0.5 + 0.5 * inc * (angle < 0 ? -1 : 1) / Math.PI;`
```
Needs different calculation?

**Comment by petrospap** [comment]
After a few calculations and tests, 
seems to me that getMoonIllumination() need to set a full Date :time or timestamp otherwise gives wrong results
my tests

```
var dt = new Date("2024-02-09T20:00:00.00Z");
//var dt = new Date("2024-02-09");
var div = document.getElementById('slot');
var para = '';
var extra = '';
var S1 = SunCalc.getMoonIllumination(dt);
var md = new Date(S1.next.newMoon.value);
var dayopt = {weekday:'short',year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'};

para += '<h2>Next New Moon: '+md.toLocaleString('en',dayopt)+'</h2>';

	for (let i = 1; i < 31; i++) {
		dt.setDate(i);
		let info=SunCalc.getMoonIllumination(dt),
		dayMoon = Math.trunc(info.phaseValue * 29.53058770576);
		extra = (dayMoon === 0 || dayMoon === 1 || dayMoon === 29) ? 'phaseValue > '+info.phaseValue : '';
		para+= '<p>Day moon = '+dayMoon+' '+info.phase.emoji+' '+dt.toLocaleString('en',dayopt)+' '+extra+'</p>';
	};
	
div.innerHTML = para;
```

In my PC says

> Next New Moon: Sun, Mar 10, 2024, 10:43:50 AM
> Day moon = 21 🌗 Thu, Feb 1, 2024, 10:00:00 PM
> Day moon = 22 🌗 Fri, Feb 2, 2024, 10:00:00 PM
> Day moon = 23 🌗 Sat, Feb 3, 2024, 10:00:00 PM
> Day moon = 24 🌘 Sun, Feb 4, 2024, 10:00:00 PM
> Day moon = 25 🌘 Mon, Feb 5, 2024, 10:00:00 PM
> Day moon = 26 🌘 Tue, Feb 6, 2024, 10:00:00 PM
> Day moon = 27 🌘 Wed, Feb 7, 2024, 10:00:00 PM
> Day moon = 28 🌘 Thu, Feb 8, 2024, 10:00:00 PM
> Day moon = 29 🌚 Fri, Feb 9, 2024, 10:00:00 PM phaseValue > 0.9869340148714654
> Day moon = 1 🌒 Sat, Feb 10, 2024, 10:00:00 PM phaseValue > 0.03422037458855848
> Day moon = 2 🌒 Sun, Feb 11, 2024, 10:00:00 PM
> Day moon = 3 🌒 Mon, Feb 12, 2024, 10:00:00 PM
> Day moon = 4 🌒 Tue, Feb 13, 2024, 10:00:00 PM
> Day moon = 5 🌒 Wed, Feb 14, 2024, 10:00:00 PM
> Day moon = 6 🌓 Thu, Feb 15, 2024, 10:00:00 PM
> Day moon = 7 🌓 Fri, Feb 16, 2024, 10:00:00 PM
> Day moon = 8 🌔 Sat, Feb 17, 2024, 10:00:00 PM
> Day moon = 9 🌔 Sun, Feb 18, 2024, 10:00:00 PM
> Day moon = 10 🌔 Mon, Feb 19, 2024, 10:00:00 PM
> Day moon = 11 🌔 Tue, Feb 20, 2024, 10:00:00 PM
> Day moon = 12 🌔 Wed, Feb 21, 2024, 10:00:00 PM
> Day moon = 13 🌔 Thu, Feb 22, 2024, 10:00:00 PM
> Day moon = 14 🌝 Fri, Feb 23, 2024, 10:00:00 PM
> Day moon = 15 🌝 Sat, Feb 24, 2024, 10:00:00 PM
> Day moon = 15 🌖 Sun, Feb 25, 2024, 10:00:00 PM
> Day moon = 16 🌖 Mon, Feb 26, 2024, 10:00:00 PM
> Day moon = 17 🌖 Tue, Feb 27, 2024, 10:00:00 PM
> Day moon = 18 🌖 Wed, Feb 28, 2024, 10:00:00 PM
> Day moon = 19 🌖 Thu, Feb 29, 2024, 10:00:00 PM
> Day moon = 20 🌖 Fri, Mar 1, 2024, 10:00:00 PM 

Thanks, and hope to find solution for phaseValue!
